name: WhisperCut
options:
  bundleIdPrefix: com.whispercut
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  whisper:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.9.0"

targets:
  WhisperCut:
    type: application
    platform: macOS
    sources:
      - path: AutoFCPXCaptions
        excludes:
          - "**/.DS_Store"
          - "**/Package.swift"
    dependencies:
      - package: whisper
        product: WhisperKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.whispercut.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.video"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 WhisperCut. All rights reserved."
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    entitlements:
      path: AutoFCPXCaptions/AutoFCPXCaptions.entitlements
